### ISSUE TITLE
version 1.1.2.24 crashes client

### ISSUE THREAD

**Issue by kreezxil** [Lunatrius/LunatriusCore#10]
something about incompatible class change error and laser level

crash report: http://paste.ee/p/NXE8C
fml client latest: http://paste.ee/p/di7qO

**Comment by Lunatrius** [comment]
Knew that would cause issues somewhere. Urgh.

**Comment by Lunatrius** [comment]
Fixed in 86d41d6bfe0e3ea5ef2168e353b881f11a685243
