### ISSUE TITLE
LunatriusCore Crash - 1.8, Win8, No mods

### ISSUE THREAD

**Issue by DaveX10** [Lunatrius/LunatriusCore#12]
**Mod version:** 1.1.2.29
**Forge version:** 11.14.4.1572
**Operating system:** Windows 8
**Crash report:** http://pastebin.com/BSpCW3gK

**Notes:** Tried downloading from multiple sources provided on the forums, no luck with any version. Tried with a fresh Forge install with no other mods, still no success. Forge ran fine before adding the mod in.

**Comment by Lunatrius** [comment]
Already fixed in f3cecbf5dff19e2dab83e245fe203650b2bb2e7e for 1.8.8. For 1.8 set `B:replaceInGameConfig=false` in the config file.
