### ISSUE TITLE
NoSuchMethodError: FMLControlledNamespacedRegistry

### ISSUE THREAD

**Issue by CA2020** [Lunatrius/LunatriusCore#15]
READ THIS
---
Your game will crash with `java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry` if you use Forge 1817 or newer. To avoid this please **use Forge 1816 or earlier**. The long story short, Forge 1.9 is rapidly changing things and I don't feel like pushing out *recompiles* for stuff that works in older versions.

*Having multiple, recompiled version would increase the amount of crashes due to an invalid Forge version - it's just easier this way.* Once we get 1.9.3 things should hopefully be stable again.
-- @Lunatrius

---

InGameInfoXML-1.9-2.8.1.81-universal
LunatriusCore-1.9-1.1.2.33-universal

http://pastebin.com/nMJNUudx

Instance crash on launch.

**Comment by Lunatrius** [comment]
I've edited the issue description with the description of why it happens and how to fix it (temporarily).

**Comment by Lunatrius** [comment]
Fixed in `1.1.2.34`.

**Comment by CA2020** [comment]
Thanks. Yes it's crazy how fast Forge is updating, even like 15 updates on the same day "insane". But for some days it has been "stable" on 1863 and nor after some days on 1864
Hopefully we get Stable 1.9.3 soon and things will be much easier :D

Thanks once again.
