### ISSUE TITLE
Stupid 1.8.8 problem

### ISSUE THREAD

**Issue by alaaemad15** [Lunatrius/LunatriusCore#18]
Whenever I attempt to even launch the game on 1.8.8 it gives me

![](https://i.gyazo.com/381158ab5e400c2fdc0fb40f0975a64e.png)

**Comment by RedNesto** [comment]
Seems you are using LunatriusCore for 1.8 and not 1.8.8. Try [this one](https://minecraft.curseforge.com/projects/lunatriuscore/files/2271762/download)

**Comment by Lunatrius** [comment]
Either download LunatriusCore for 1.8.8 or downgrade Minecraft to 1.8.

**Comment by alaaemad15** [comment]
I found the issue, the 1.8.8 version of the mod on mod.io is incorrect.

**Comment by Lunatrius** [comment]
Are you sure that you downloaded version `1.1.2.31`?
